kind: pipeline
name: default

steps:
- name: test
  image: python:3.6
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - pip install poetry
  - poetry install --extras=bitvector
  - poetry run pytest --flake8 --cov=aiger_sat
  - poetry run codecov
