[tool.poetry]
name = "aiger_sat"
readme="README.md"
version = "0.1.0"
description = "Pythonic interface between AIGs and SAT solvers."
authors = ["Marcell Vazquez-Chanlatte <mvc@linux.com>"]
packages = [
    { include = "aiger_sat" },
]

[tool.poetry.dependencies]
python = "^3.7"
python-sat = "0.1.4.dev13"
py-aiger = "^3.3"

[tool.poetry.dev-dependencies]
codecov = "^2.0"
pytest = "^5.0"
pytest-flake8 = "^1.0"
pytest-sugar = "^0.9.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
